package id.co.akuntansiku.utils.model;

public class DataPreference {
    String AKUNTANSIKU_API_TOKEN;
    String AKUNTANSIKU_API_TOKEN_TYPE;
    String AKUNTANSIKU_API_REFRESH_TOKEN;

    int AKUNTANSIKU_USER_ID;
    String AKUNTANSIKU_USER_NAME;
    String AKUNTANSIKU_USER_EMAIL;
    String AKUNTANSIKU_USER_ROLE;
    int AKUNTANSIKU_USER_DEFAULT_COMPANY_WEB;

    public DataPreference() {
    }

    public String getAKUNTANSIKU_API_TOKEN() {
        return AKUNTANSIKU_API_TOKEN;
    }

    public void setAKUNTANSIKU_API_TOKEN(String AKUNTANSIKU_API_TOKEN) {
        this.AKUNTANSIKU_API_TOKEN = AKUNTANSIKU_API_TOKEN;
    }

    public String getAKUNTANSIKU_API_TOKEN_TYPE() {
        return AKUNTANSIKU_API_TOKEN_TYPE;
    }

    public void setAKUNTANSIKU_API_TOKEN_TYPE(String AKUNTANSIKU_API_TOKEN_TYPE) {
        this.AKUNTANSIKU_API_TOKEN_TYPE = AKUNTANSIKU_API_TOKEN_TYPE;
    }

    public String getAKUNTANSIKU_API_REFRESH_TOKEN() {
        return AKUNTANSIKU_API_REFRESH_TOKEN;
    }

    public void setAKUNTANSIKU_API_REFRESH_TOKEN(String AKUNTANSIKU_API_REFRESH_TOKEN) {
        this.AKUNTANSIKU_API_REFRESH_TOKEN = AKUNTANSIKU_API_REFRESH_TOKEN;
    }

    public int getAKUNTANSIKU_USER_ID() {
        return AKUNTANSIKU_USER_ID;
    }

    public void setAKUNTANSIKU_USER_ID(int AKUNTANSIKU_USER_ID) {
        this.AKUNTANSIKU_USER_ID = AKUNTANSIKU_USER_ID;
    }

    public String getAKUNTANSIKU_USER_NAME() {
        return AKUNTANSIKU_USER_NAME;
    }

    public void setAKUNTANSIKU_USER_NAME(String AKUNTANSIKU_USER_NAME) {
        this.AKUNTANSIKU_USER_NAME = AKUNTANSIKU_USER_NAME;
    }

    public String getAKUNTANSIKU_USER_EMAIL() {
        return AKUNTANSIKU_USER_EMAIL;
    }

    public void setAKUNTANSIKU_USER_EMAIL(String AKUNTANSIKU_USER_EMAIL) {
        this.AKUNTANSIKU_USER_EMAIL = AKUNTANSIKU_USER_EMAIL;
    }

    public String getAKUNTANSIKU_USER_ROLE() {
        return AKUNTANSIKU_USER_ROLE;
    }

    public void setAKUNTANSIKU_USER_ROLE(String AKUNTANSIKU_USER_ROLE) {
        this.AKUNTANSIKU_USER_ROLE = AKUNTANSIKU_USER_ROLE;
    }

    public int getAKUNTANSIKU_USER_DEFAULT_COMPANY_WEB() {
        return AKUNTANSIKU_USER_DEFAULT_COMPANY_WEB;
    }

    public void setAKUNTANSIKU_USER_DEFAULT_COMPANY_WEB(int AKUNTANSIKU_USER_DEFAULT_COMPANY_WEB) {
        this.AKUNTANSIKU_USER_DEFAULT_COMPANY_WEB = AKUNTANSIKU_USER_DEFAULT_COMPANY_WEB;
    }
}
